M48
; DRILL file {KiCad (6.0.1-0)} date 2022 May 02, Monday 12:36:34
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-02T12:36:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
%
G90
G05
T1
X4.8307Y-0.8307
X4.8319Y-1.3189
X5.0669Y-0.8307
X5.0681Y-1.3189
T0
M30
